// src/pages/Overview.svelte
<script lang="ts">
  import { useReport, useReportTime, reportStaleTime } from "$lib/reports";
  import { effectiveEnd } from "$lib/api";
  import { createQuery } from "@tanstack/svelte-query";
  import {
    Bell,
    Search,
    ChevronRight,
    Database,
    Landmark,
    TrendingUp,
    Wallet,
    ReceiptText,
    Eye,
    EyeOff,
  } from "@lucide/svelte";
  import { Button } from "$lib/components/ui/button";
  import { useApi, useAccounts } from "$lib/context";
  import { currentMonth, money, monthRange } from "$lib/finance";
  import { transactionMoney, transactionCategory } from "$lib/presentation";
  import { router } from "$lib/router.svelte";
  import Field from "../components/Field.svelte";
  import Loading from "../components/Loading.svelte";
  import Failure from "../components/Failure.svelte";
  import Empty from "../components/Empty.svelte";
  import Trend from "../components/Trend.svelte";
  import Cashflow from "../components/Cashflow.svelte";
  import TransactionIcon from "../components/TransactionIcon.svelte";
  import BalanceSparkline from "../components/BalanceSparkline.svelte";
  let {
    hidden,
    onToggleAmounts,
  }: { hidden: boolean; onToggleAmounts?: () => void } = $props();
  let localHidden = $state(false);
  let masked = $derived(hidden || localHidden);
  let month = $state(currentMonth());
  let view = $state("overview");
  let cashMode = $state<"future" | "month">("future");
  const api = useApi();
  const accounts = useAccounts();
  const now = useReportTime();
  let range = $derived(monthRange(month));
  let cutoff = $derived(effectiveEnd(range.end, now));
  const period = () => ({ ...range, asOf: now });
  const balance = useReport(
    "balance",
    period,
    () => view === "overview" || view === "assets",
  );
  const income = useReport(
    "income",
    period,
    () => view === "overview" || view === "profit",
  );
  const quality = useReport("quality", period);
  const balances = useReport("accounts", period, () => view === "assets");
  const categories = useReport("categories", period, () => view === "profit");
  const trend = useReport("trend", period, () => view === "profit" && !masked);
  let active = $derived([
    quality,
    ...(view === "overview" || view === "assets" ? [balance] : []),
    ...(view === "overview" || view === "profit" ? [income] : []),
    ...(view === "assets" ? [balances] : []),
    ...(view === "profit" ? [categories, ...(!masked ? [trend] : [])] : []),
  ]);
  let query = $derived({
    isPending: active.some((q) => q.isPending),
    error: active.find((q) => q.error)?.error,
    refetch: () =>
      Promise.all(active.filter((q) => q.isError).map((q) => q.refetch())),
  });
  let data = $derived({
    as_of: cutoff,
    net_assets: balance.data?.net_assets ?? "0",
    assets: balance.data?.assets ?? "0",
    liabilities: balance.data?.liabilities ?? "0",
    income: income.data?.income ?? "0",
    expense: income.data?.expense ?? "0",
    profit: income.data?.profit ?? "0",
    quality: { pending: quality.data?.pending ?? 0 },
    accounts: balances.data ?? [],
    categories: categories.data ?? [],
    trend: trend.data ?? [],
  });
  const recent = createQuery(() => ({
    queryKey: ["transactions", "recent", 3],
    queryFn: () => api.list({}, null, 3),
    enabled: view === "overview",
    staleTime: reportStaleTime,
  }));
  function down(filters: Record<string, string>) {
    router.navigate(
      "/transactions?" +
        new URLSearchParams({
          start: range.start,
          end: data?.as_of ?? range.end,
          posted: "true",
          ...filters,
        }),
    );
  }
  function toggleAmounts() {
    if (onToggleAmounts) onToggleAmounts();
    else localHidden = !localHidden;
  }
</script>

<div class="page">
  <div class="page-heading pr-12">
    <h1>个人财务</h1>
    <div class="flex items-center gap-1">
      <Button
        href="/transactions"
        variant="ghost"
        size="icon"
        aria-label="搜索流水"
        ><Search class="size-6" aria-hidden="true" /></Button
      >
      <Button
        href="/transactions?review=needed"
        variant="ghost"
        size="icon"
        class="relative"
        aria-label={quality.data
          ? `待补录 ${data.quality.pending} 笔`
          : "待补录"}
        ><Bell
          class="size-6"
          aria-hidden="true"
        />{#if data && data.quality.pending > 0}<span
            class="absolute top-1 right-1 size-2 rounded-full bg-cash-out"
            aria-hidden="true"
          ></span>{/if}</Button
      >
    </div>
  </div>
  <div class="flex items-center justify-between gap-3">
    <div
      class="flex min-w-0 flex-1 rounded-full bg-card/80 p-1"
      role="group"
      aria-label="报表视图"
    >
      {#each [["overview", "总览"], ["assets", "资产负债"], ["cash", "现金流量"], ["profit", "损益"]] as [key, label]}<Button
          class="min-w-0 flex-1 rounded-full px-2"
          variant={view === key ? "default" : "ghost"}
          aria-pressed={view === key}
          onclick={() => (view = key)}>{label}</Button
        >{/each}
    </div>
    <div class="hidden max-w-40 sm:block">
      <Field
        label="报表月份"
        type="month"
        compact
        max={currentMonth()}
        value={month}
        onchange={(e) => {
          if (
            /^\d{4}-\d{2}$/.test(e.currentTarget.value) &&
            e.currentTarget.value <= currentMonth()
          )
            month = e.currentTarget.value;
        }}
      />
    </div>
  </div>
  {#if query.isPending}<Loading />{:else if query.error}<Failure
      error={query.error}
      retry={() => query.refetch()}
    />{:else if data}
    <div class="flex justify-end sm:hidden">
      <Field
        label="报表月份"
        type="month"
        compact
        max={currentMonth()}
        value={month}
        onchange={(e) => {
          if (
            /^\d{4}-\d{2}$/.test(e.currentTarget.value) &&
            e.currentTarget.value <= currentMonth()
          )
            month = e.currentTarget.value;
        }}
      />
    </div>
    {#if view === "overview" || view === "assets"}
      <section
        class="finance-card relative overflow-hidden p-5 sm:p-7"
        aria-label="净资产"
      >
        {#if !masked}<div
            class="pointer-events-none absolute right-0 bottom-0 w-1/2 opacity-65"
          >
            <BalanceSparkline
              start={range.start}
              end={data.as_of}
              closing={data.net_assets}
            />
          </div>{/if}
        <div class="relative">
          <div class="flex items-center gap-3">
            <span class="icon-tile bg-asset/10 text-asset"
              ><Database class="size-5" aria-hidden="true" /></span
            >
            <h2>净资产</h2>
            <Button
              variant="ghost"
              size="icon"
              aria-label={masked ? "显示金额" : "隐藏金额"}
              onclick={toggleAmounts}
              >{#if masked}<EyeOff aria-hidden="true" />{:else}<Eye
                  aria-hidden="true"
                />{/if}</Button
            >
          </div>
          <p class="money mt-4 break-words text-4xl font-semibold sm:text-5xl">
            {money(data.net_assets, masked)}
          </p>
        </div>
      </section>
      <div class="grid grid-cols-2 gap-3 sm:gap-4">
        {#each [{ type: "资产", title: "总资产", value: data.assets, icon: Wallet, color: "bg-asset/10 text-asset" }, { type: "负债", title: "总负债", value: data.liabilities, icon: Landmark, color: "bg-cash-out/10 text-cash-out" }] as item}
          <button
            class="finance-card min-w-0 p-4 text-left transition-colors hover:bg-accent sm:p-5"
            onclick={() => down({ account_type: item.type, start: "" })}
            ><span class="flex items-center gap-2"
              ><span class={`icon-tile ${item.color}`}
                ><item.icon class="size-5" aria-hidden="true" /></span
              ><span class="font-medium">{item.title}</span><ChevronRight
                class="ml-auto size-4 text-muted-foreground"
                aria-hidden="true"
              /></span
            ><span
              class="money mt-3 block break-words text-xl font-semibold sm:text-2xl"
              >{money(item.value, masked)}</span
            ></button
          >
        {/each}
      </div>
    {/if}
    {#if view === "overview" || view === "cash"}<Cashflow
        hidden={masked}
        asOf={data.as_of}
        bind:mode={cashMode}
        {range}
        {now}
      />{/if}
    {#if view === "overview" || view === "profit"}
      <section class="finance-card p-5 sm:p-6" aria-label="本期损益">
        <div class="mb-5 flex items-center justify-between">
          <h2 class="flex items-center gap-3">
            <span class="icon-tile bg-profit/10 text-profit"
              ><TrendingUp class="size-5" aria-hidden="true" /></span
            >损益
          </h2>
          {#if view === "overview"}<Button
              variant="ghost"
              size="icon"
              aria-label="查看损益明细"
              onclick={() => (view = "profit")}
              ><ChevronRight aria-hidden="true" /></Button
            >{/if}
        </div>
        <div class="grid grid-cols-3 divide-x">
          <div class="min-w-0 pr-3">
            <p class="text-sm text-muted-foreground">本月收入</p>
            <button
              class="money mt-1 min-h-12 break-words text-left font-semibold sm:text-2xl"
              onclick={() => down({ account_type: "收入" })}
              >{money(data.income, masked)}</button
            >
          </div>
          <div class="min-w-0 px-3">
            <p class="text-sm text-muted-foreground">本月支出</p>
            <button
              class="money mt-1 min-h-12 break-words text-left font-semibold sm:text-2xl"
              onclick={() => down({ account_type: "支出" })}
              >{money(data.expense, masked)}</button
            >
          </div>
          <div class="min-w-0 pl-3">
            <p class="text-sm text-muted-foreground">本月利润</p>
            <p
              class="money mt-1 min-h-12 content-center break-words font-semibold sm:text-2xl"
            >
              {money(data.profit, masked)}
            </p>
          </div>
        </div>
      </section>
    {/if}
    {#if view === "overview"}
      <section class="finance-card p-5 sm:p-6" aria-label="最近交易">
        <div class="flex items-center justify-between">
          <h2 class="flex items-center gap-3">
            <span class="icon-tile bg-muted text-muted-foreground"
              ><ReceiptText class="size-5" aria-hidden="true" /></span
            >最近交易
          </h2>
          <Button href="/transactions" variant="ghost"
            >查看全部<ChevronRight aria-hidden="true" /></Button
          >
        </div>
        {#if recent.isPending}<Loading />{:else if recent.error}<Failure
            error={recent.error}
            retry={() => recent.refetch()}
          />{:else if !recent.data?.items.length}<Empty title="暂无交易"
            ><Button href="/transactions/new">记一笔</Button></Empty
          >{:else}
          <div class="mt-2 divide-y">
            {#each recent.data.items.slice(0, 3) as t}<a
                href={`/transactions/${t.id}`}
                class="flex min-w-0 items-center gap-3 py-4"
                ><TransactionIcon
                  category={transactionCategory(t, accounts.data ?? [])}
                  kind={t.kind}
                /><span class="min-w-0 flex-1"
                  ><span class="block truncate font-medium"
                    >{t.merchant || t.notes || "未命名交易"}</span
                  ><span class="mt-1 block text-sm text-muted-foreground"
                    >{new Date(t.occurred_at).toLocaleDateString("zh-CN", {
                      timeZone: "Asia/Shanghai",
                      month: "long",
                      day: "numeric",
                    })}</span
                  ></span
                ><span
                  class="money max-w-[45%] break-words text-right font-semibold"
                  class:text-cash-in={t.kind === "income" ||
                    t.kind === "refund"}
                  >{t.amount === null
                    ? "待补录"
                    : transactionMoney(t, masked)}</span
                ><ChevronRight
                  class="size-4 shrink-0 text-muted-foreground"
                  aria-hidden="true"
                /></a
              >{/each}
          </div>
        {/if}
      </section>
    {/if}
    {#if view === "profit"}<section
        class="finance-card space-y-4 p-5"
        aria-label="损益明细"
      >
        {#if masked}<div class="grid h-40 place-items-center">
            <EyeOff
              class="size-8 text-muted-foreground"
              aria-label="金额已隐藏"
            />
          </div>{:else if data.trend.length}<Trend
            data={data.trend}
          />{:else}<Empty
            title="暂无收支"
          />{/if}{#each data.categories as c}<button
            class="flex min-h-12 w-full justify-between gap-3 border-t py-3 text-left"
            onclick={() => down({ account_type: c.type })}
            ><span>{c.type} · {c.name}</span><span class="money"
              >{money(c.amount, masked)}</span
            ></button
          >{/each}
      </section>{/if}
    {#if view === "assets"}<section
        class="finance-card divide-y p-5"
        aria-label="科目余额"
      >
        {#each data.accounts.filter( (a) => ["资产", "负债"].includes(a.type) ) as a}<button
            class="flex min-h-16 w-full items-center justify-between gap-3 py-3 text-left"
            onclick={() => down({ account_id: String(a.id), start: "" })}
            ><span
              ><span class="block font-medium">{a.name}</span><span
                class="text-sm text-muted-foreground"
                >{a.type} · {a.subtype}</span
              ></span
            ><span class="money">{money(a.balance, masked)}</span></button
          >{:else}<Empty title="暂无余额"
            ><Button href="/transactions/new">记一笔</Button></Empty
          >{/each}
      </section>{/if}
  {/if}
</div>

// src/pages/Overview.tsx
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useNavigate } from "react-router-dom";
import {
  Alert,
  Box,
  Button,
  Card,
  CardActionArea,
  CardContent,
  Chip,
  Divider,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import {
  ArrowForward,
  ArrowDownward,
  ArrowUpward,
  AccountBalanceWalletOutlined,
} from "@mui/icons-material";
import {
  Area,
  AreaChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
} from "recharts";
import { useApi, useAccounts } from "../lib/api";
import {
  categoryLabels,
  currentMonth,
  money,
  monthRange,
} from "../lib/finance";

import { Loading, Failure, Empty } from "../components/State";
export default function OverviewPage({ hidden }: { hidden: boolean }) {
  const [month, setMonth] = useState(currentMonth);
  const api = useApi();
  const accounts = useAccounts();
  const cashConfigured = !!accounts.data?.some(
    (a) => a.type === "资产" && a.subtype === "现金及等价物",
  );
  const range = monthRange(month);
  const nav = useNavigate();
  const query = useQuery({
    queryKey: ["overview", month],
    queryFn: () =>
      api.overview(range.start, range.end, new Date().toISOString()),
  });
  const down = (filters: Record<string, string>) =>
    nav(
      "/transactions?" +
        new URLSearchParams({
          start: range.start,
          end: range.end,
          posted: "true",
          ...filters,
        }),
    );
  const data = query.data;
  return (
    <Stack spacing={3} className="page">
      <Stack
        direction="row"
        spacing={2}
        sx={{ alignItems: "center", justifyContent: "space-between" }}
      >
        <Box>
          <Typography variant="h4">财务总览</Typography>
          <Typography color="text.secondary" sx={{ mt: 1 }}>
            收支有迹，生活有序。
          </Typography>
        </Box>
        <TextField
          label="报表月份"
          type="month"
          value={month}
          onChange={(e) => {
            if (/^\d{4}-\d{2}$/.test(e.target.value)) setMonth(e.target.value);
          }}
          sx={{ maxWidth: 175 }}
          slotProps={{ inputLabel: { shrink: true } }}
        />
      </Stack>
      {query.isPending ? (
        <Loading />
      ) : query.error ? (
        <Failure error={query.error} retry={() => query.refetch()} />
      ) : (
        data && (
          <>
            {
              <Alert
                severity="info"
                action={
                  <Button
                    component={Link}
                    to="/transactions?review=needed"
                    color="inherit"
                  >
                    去核对
                  </Button>
                }
              >
                {data.quality.pending}{" "}
                笔交易待补录。以下仅反映完整交易的已记录范围，请核对期初覆盖情况。
              </Alert>
            }
            <Card
              sx={{
                bgcolor: "primary.main",
                color: "primary.contrastText",
                border: 0,
              }}
            >
              <CardContent sx={{ p: { xs: 3, sm: 4 } }}>
                <Stack
                  direction="row"
                  sx={{ justifyContent: "space-between", alignItems: "center" }}
                >
                  <Typography>已记录净资产</Typography>
                  <AccountBalanceWalletOutlined />
                </Stack>
                <Typography
                  className="money"
                  sx={{
                    fontSize: { xs: 36, sm: 48 },
                    fontWeight: 700,
                    mt: 1,
                    mb: 1,
                  }}
                >
                  {money(data.net_assets, hidden)}
                </Typography>
                <Typography variant="body2" sx={{ opacity: 0.85 }}>
                  截至{" "}
                  {new Date(data.as_of).toLocaleDateString("zh-CN", {
                    timeZone: "Asia/Shanghai",
                  })}{" "}
                  · 人民币 · 账面余额
                </Typography>
                <Divider
                  sx={{ my: 3, borderColor: "currentColor", opacity: 0.2 }}
                />
                <Stack direction="row" spacing={5}>
                  <Box>
                    <Typography variant="body2">资产</Typography>
                    <Button
                      color="inherit"
                      sx={{ px: 0, fontSize: 20 }}
                      onClick={() => down({ account_type: "资产", start: "" })}
                    >
                      {money(data.assets, hidden)}
                    </Button>
                  </Box>
                  <Box>
                    <Typography variant="body2">负债</Typography>
                    <Button
                      color="inherit"
                      sx={{ px: 0, fontSize: 20 }}
                      onClick={() => down({ account_type: "负债", start: "" })}
                    >
                      {money(data.liabilities, hidden)}
                    </Button>
                  </Box>
                </Stack>
              </CardContent>
            </Card>
            <Box
              sx={{
                display: "grid",
                gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" },
                gap: 3,
              }}
            >
              <Card>
                <CardContent sx={{ p: 3 }}>
                  <Stack
                    direction="row"
                    sx={{
                      alignItems: "center",
                      justifyContent: "space-between",
                    }}
                  >
                    <Typography variant="h6">现金流量</Typography>
                    <Button
                      endIcon={<ArrowForward />}
                      onClick={() => down({ cash: "true" })}
                    >
                      查看流水
                    </Button>
                  </Stack>
                  {!cashConfigured && (
                    <Alert severity="warning" sx={{ my: 1 }}>
                      未找到“资产 / 现金及等价物”科目。
                    </Alert>
                  )}
                  <Typography variant="body2" color="text.secondary">
                    净流入
                  </Typography>
                  <Typography variant="h4" className="money" sx={{ my: 1 }}>
                    {cashConfigured ? money(data.cash_net, hidden) : "待确认"}
                  </Typography>
                  <Stack
                    direction="row"
                    sx={{ justifyContent: "space-between", my: 2 }}
                  >
                    <Stack spacing={1}>
                      <Typography color="text.secondary">
                        <ArrowDownward sx={{ fontSize: 16 }} /> 对外流入
                      </Typography>
                      <Typography sx={{ fontWeight: 650 }}>
                        {cashConfigured ? money(data.cash_in, hidden) : "—"}
                      </Typography>
                    </Stack>
                    <Stack spacing={1}>
                      <Typography color="text.secondary">
                        <ArrowUpward sx={{ fontSize: 16 }} /> 对外流出
                      </Typography>
                      <Typography sx={{ fontWeight: 650 }}>
                        {cashConfigured ? money(data.cash_out, hidden) : "—"}
                      </Typography>
                    </Stack>
                  </Stack>
                  <Divider sx={{ my: 2 }} />
                  {cashConfigured &&
                    data.cash_categories.map((c) => (
                      <Stack
                        key={c.name}
                        direction="row"
                        sx={{ justifyContent: "space-between", my: 1 }}
                      >
                        <Typography color="text.secondary">
                          {categoryLabels[c.name]}
                        </Typography>
                        <Typography variant="body2">
                          入 {money(c.inflow, hidden)} / 出{" "}
                          {money(c.outflow, hidden)}
                        </Typography>
                      </Stack>
                    ))}
                  <Typography variant="caption" color="text.secondary">
                    现金流按每笔交易现金净变化计算，现金内部转账净额为零。
                  </Typography>
                </CardContent>
              </Card>
              <Card>
                <CardContent sx={{ p: 3 }}>
                  <Stack
                    direction="row"
                    sx={{
                      justifyContent: "space-between",
                      alignItems: "center",
                    }}
                  >
                    <Typography variant="h6">本期损益</Typography>
                    <Chip label="完整记录口径" size="small" />
                  </Stack>
                  <Typography
                    variant="body2"
                    color="text.secondary"
                    sx={{ mt: 2 }}
                  >
                    净收益
                  </Typography>
                  <Typography className="money" variant="h4" sx={{ my: 1 }}>
                    {money(data.profit, hidden)}
                  </Typography>
                  <Stack direction="row" spacing={4} sx={{ my: 2 }}>
                    <Box>
                      <Typography color="text.secondary">收入</Typography>
                      <Button onClick={() => down({ account_type: "收入" })}>
                        {money(data.income, hidden)}
                      </Button>
                    </Box>
                    <Box>
                      <Typography color="text.secondary">支出</Typography>
                      <Button onClick={() => down({ account_type: "支出" })}>
                        {money(data.expense, hidden)}
                      </Button>
                    </Box>
                  </Stack>
                  <Typography variant="caption" color="text.secondary">
                    信用卡消费计入支出，还款不重复计入损益。
                  </Typography>
                </CardContent>
              </Card>
            </Box>
            <Card>
              <CardContent sx={{ p: 3 }}>
                <Typography variant="h6" gutterBottom>
                  本月收支趋势
                </Typography>
                {hidden ? (
                  <Box
                    sx={{ height: 200, display: "grid", placeItems: "center" }}
                  >
                    金额已隐藏
                  </Box>
                ) : data.trend.length === 0 ? (
                  <Typography
                    color="text.secondary"
                    sx={{ py: 5, textAlign: "center" }}
                  >
                    本月暂无完整记录交易。先去核对流水。
                  </Typography>
                ) : (
                  <Box
                    sx={{ height: 240 }}
                    role="img"
                    aria-label="本月完整记录收入及支出趋势，明细见下方类别"
                  >
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart
                        data={data.trend.map((d) => ({
                          ...d,
                          income: Number(d.income),
                          expense: Number(d.expense),
                        }))}
                      >
                        <CartesianGrid vertical={false} strokeDasharray="3 3" />
                        <XAxis
                          dataKey="date"
                          tickFormatter={(v) => v.slice(5)}
                          tick={{ fontSize: 12 }}
                        />
                        <Tooltip
                          formatter={(v, name) => [
                            money(String(v)),
                            name === "income" ? "收入" : "支出",
                          ]}
                        />
                        <Area
                          dataKey="income"
                          name="income"
                          stroke="#2458A6"
                          fill="#2458A6"
                          fillOpacity={0.12}
                          isAnimationActive={false}
                        />
                        <Area
                          dataKey="expense"
                          name="expense"
                          stroke="#A96B29"
                          fill="#A96B29"
                          fillOpacity={0.06}
                          isAnimationActive={false}
                        />
                      </AreaChart>
                    </ResponsiveContainer>
                  </Box>
                )}
                {data.categories.map((c) => (
                  <Stack
                    key={c.type + c.name}
                    direction="row"
                    sx={{ justifyContent: "space-between", py: 1 }}
                  >
                    <Typography>
                      {c.type} · {c.name}
                    </Typography>
                    <Typography>{money(c.amount, hidden)}</Typography>
                  </Stack>
                ))}
              </CardContent>
            </Card>
            <Stack spacing={1}>
              <Typography variant="h6">科目余额</Typography>
              {data.accounts.length === 0 ? (
                <Empty
                  title="等待第一笔正式入账"
                  description="补全历史流水后，资产负债与损益会按统一口径自动更新。"
                />
              ) : (
                data.accounts
                  .filter((a) => ["资产", "负债"].includes(a.type))
                  .map((a) => (
                    <Card key={a.id}>
                      <CardActionArea
                        onClick={() =>
                          down({ account_id: String(a.id), start: "" })
                        }
                      >
                        <CardContent
                          sx={{
                            display: "flex",
                            justifyContent: "space-between",
                            gap: 2,
                          }}
                        >
                          <Box>
                            <Typography sx={{ fontWeight: 600 }}>
                              {a.name}
                            </Typography>
                            <Typography variant="body2" color="text.secondary">
                              {a.type} / {a.subtype}
                            </Typography>
                          </Box>
                          <Typography
                            className="money"
                            sx={{ alignSelf: "center" }}
                          >
                            {money(a.balance, hidden)}
                          </Typography>
                        </CardContent>
                      </CardActionArea>
                    </Card>
                  ))
              )}
            </Stack>
            <Typography variant="caption" color="text.secondary">
              完整记录 {data.quality.posted} 笔 · 缺少分录{" "}
              {data.quality.missing_entries} 笔 · 缺少科目{" "}
              {data.quality.missing_accounts} 笔
            </Typography>
          </>
        )
      )}
    </Stack>
  );
}
